# Generated by Django 3.0.6 on 2020-06-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200613_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Thumbnail_image',
            field=models.ImageField(blank=True, upload_to='blog/images/blog_thumbnail_images'),
        ),
    ]
