# Generated by Django 3.0.6 on 2020-06-05 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('home', '0002_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_pic', models.ImageField(default='home/images/userprofileimages/defaultuser.png', upload_to='home/images/userprofileimages')),
            ],
        ),
    ]
