# Generated by Django 3.0.6 on 2020-06-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productUniquename',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
