# Generated by Django 3.0.6 on 2020-06-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200611_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='profile_pic',
            field=models.ImageField(default='static/img/defaultuser.png', upload_to='home/images/userprofileimages'),
        ),
    ]
