# Generated by Django 3.0.6 on 2020-06-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200613_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='profile_pic',
            field=models.ImageField(default='home/images/userprofileimages/defaultuser.png', upload_to='home/images/userprofileimages'),
        ),
    ]
